on:
  push:
    branches:
      - main

name: Update GitHub Pages

env:
  CARGO_INCREMENTAL: 0

jobs:
  pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features --no-deps
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc
          CLEAN: true # Automatically remove deleted files from the deploy branch
